rails/config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :communities, only: [:index, :show] do
      resources :stories, only: [:index, :show]
      resources :places, only: [:show]
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    scope '/member', module: 'dashboard', constraints: RoleRoutingConstraint.new { |user| !user.super_admin } do
      root to: "stories#index", as: :member_root

      get :search, to: "search#index"

      resource :community, only: [:show, :update], as: :community_settings do
        delete :background_img, action: :delete_background_img
        delete :display_image, action: :delete_display_image
        delete '/sponsor_logo/:id/delete', action: :delete_sponsor_logo, as: :delete_sponsor_logo
      end
      resources :users do
        delete :photo, action: :delete_photo
      end
      resources :speakers do
        delete :photo, action: :delete_photo
      end
      resources :places do
        delete :photo, action: :delete_photo
        delete :name_audio, action: :delete_name_audio
      end
      resources :stories do
        delete '/media/:id/delete', action: :delete_media, as: :delete_media
      end
      resource :theme, only: [:update, :edit, :show]
      resource :import, only: [:show, :create] do
        post :preview
      end
    end

    # super admin resource routes
    scope '/admin', module: 'super_admin', constraints: RoleRoutingConstraint.new { |user| user.super_admin } do
      root to: "metrics#show", as: :super_admin_root

      resource :metrics, only: :show
      resources :communities
      resources :features do
        post :enable
        post :disable
      end
    end

    get :login, to: "sessions#new"
    post :login, to: "sessions#create"
    delete :logout, to: "sessions#destroy"

    get :profile, to: "profile#edit"
    patch :profile, to: "profile#update"
    get :change_password, to: "passwords#edit"
    post :change_password, to: "passwords#update"

    root to: 'welcome#index'
    get 'home', to: 'home#index', as: "home_map"
    get "search", to: "home#community_search_index", as: "community_search"

    get :onboard, to: "onboard#start", as: :start_onboarding
    namespace :onboard do
      resource :community, controller: :community, only: [:show, :create], as: :community
      resource :account, controller: :account, only: [:show, :create], as: :admin_account
    end
  end
end

rails/app/controllers/dashboard/application_controller.rb
module Dashboard
  class ApplicationController < ApplicationController
    rescue_from Pundit::NotAuthorizedError, with: :not_authorized
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    layout "dashboard"

    before_action :authenticate_user!

    protected

    def not_authorized
      flash.alert = "You are not authorized to perform this action"
      redirect_to member_root_path
    end

    def not_found
      flash.alert = "The resource you requested cannot be found"
      redirect_to member_root_path
    end

    private

    def meta_params
      params.permit(
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    rescue_from Pundit::NotAuthorizedError, with: :not_authorized
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    layout "dashboard"

    before_action :authenticate_user!

    protected

    def not_authorized
      flash.alert = "You are not authorized to perform this action"
      redirect_to member_root_path
    end

    def not_found
      flash.alert = "The resource you requested cannot be found"
      redirect_to member_root_path
    end

    private

    def meta_params
      params.permit(
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/communities_controller.rb
module Dashboard
  class CommunitiesController < BaseController
    def show
      @community = authorize current_user.community
    end

    def update
      @community = authorize current_user.community

      @community.update(community_params)

      # Append new sponsor logos
      if file_uploads.present?
        file_uploads[:sponsor_logos].each do |logo|
          @community.sponsor_logos.attach(io: logo, filename: logo.original_filename)
        end
      end

      if @community.public? && @community.theme.mapbox_token.present?
        static_map_url = if @community.theme.boundaries
          "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@community.theme.boundaries.flatten.to_s.gsub(' ','').sub("[", "%5B").sub("]", "%5D")}/900x600?access_token=#{@community.theme.mapbox_token}"
        else
          "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@community.theme.center_long},#{@community.theme.center_lat},#{@community.theme.zoom},#{@community.theme.bearing},#{@community.theme.pitch}/900x600?access_token=#{@community.theme.mapbox_token}"
        end
        begin
          @community.theme.static_map.attach(io: URI.open(static_map_url), filename: "#{@community.slug}-static-map.png")
        rescue StandardError
          # do nothing; no worries if we can't save the map
        end
      end

      redirect_to community_settings_path
    end

    def delete_background_img
      @community = authorize current_user.community, :delete_attachments?
      @community.background_img.purge

      head :ok
    end

    def delete_display_image
      @community = authorize current_user.community, :delete_attachments?
      @community.display_image.purge

      head :ok
    end

    def delete_sponsor_logo
      @community = authorize current_user.community, :delete_attachments?
      logo_blob = @community.sponsor_logos.blobs.find_signed(params[:id])
      logo_blob.attachments.each(&:purge)

      head :ok
    end

    private

    def community_params
      params.require(:community).permit(
        :beta,
        :public,
        :background_img,
        :display_image,
        :description
      )
    end

    def file_uploads
      params.require(:community).permit(sponsor_logos: [])
    end
  end
end

rails/app/controllers/dashboard/imports_controller.rb
module Dashboard
  class ImportsController < BaseController
    rescue_from Importable::FileImporter::HeaderMismatchError, with: :mapped_header_mismatch
    def show

    end

    def preview
      @model = params[:model]
      @required_headers = @model.classify.constantize&.csv_headers
      @csv = CSV.open(params[:file], headers: true) { |csv| csv.first.headers }

      render json: {
        headers: render_to_string(partial: "header_matches", formats: [:html])
      }
    end

    def create
      places_file = import_params[:places_csv]
      place_result = if places_file.present?
        place_headers = import_params[:place_headers].to_h
        Place.import(places_file, current_community.id, place_headers)
      end

      speakers_file = params[:speakers_csv]
      speaker_result = if speakers_file.present?
        speaker_headers = import_params[:speaker_headers].to_h
        Speaker.import(speakers_file, current_community.id, speaker_headers)
      end

      stories_file = params[:stories_csv]
      story_result = if stories_file.present?
        story_headers = import_params[:story_headers].to_h
        Story.import(stories_file, current_community.id, story_headers)
      end

      render locals: {
        places: place_result,
        speakers: speaker_result,
        stories: story_result
      }
    end

    private

    def import_params
      params.permit(
        :places_csv,
        :speakers_csv,
        :stories_csv,
        place_headers: Place.csv_headers,
        speaker_headers: Speaker.csv_headers,
        story_headers: Story.csv_headers
      )
    end

    def mapped_header_mismatch
      flash.alert = "Additional headers detected. Please verify your CSV headers against the resource you are importing."
      redirect_to import_path
    end
  end
end

rails/app/controllers/dashboard/places_controller.rb
module Dashboard
  class PlacesController < BaseController
    def index
      @page = PlacesPage.new(community_places, meta_params)
      @places = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "places", formats: [:html]),
            pagination: @page.has_next_page? ? places_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    def new
      # set initial position using the current community's theme
      current_theme = current_community.theme
      authorize @place = community_places.new(lat: current_theme.center_lat || 0, long: current_theme.center_long || 0)
    end

    def create
      authorize Place
      @place = community_places.new(place_params)

      if @place.save
        redirect_to @place
      else
        render :new
      end
    end

    def show
      @place = authorize community_places.find(params[:id])
    end

    def edit
      @place = authorize community_places.find(params[:id])
    end

    def update
      @place = authorize community_places.find(params[:id])

      if @place.update(place_params)
        redirect_to @place
      else
        render :edit
      end
    end

    def destroy
      @place = authorize community_places.find(params[:id])

      @place.destroy

      redirect_to places_path
    end

    def delete_photo
      @place = authorize community_places.find(params[:place_id])
      @place.photo.purge

      head :ok
    end

    def delete_name_audio
      @place = authorize community_places.find(params[:place_id])
      @place.name_audio.purge

      head :ok
    end

    private

    def community_places
      policy_scope(current_community.places)
    end

    def place_params
      params.require(:place).permit(
        :name,
        :description,
        :photo,
        :name_audio,
        :type_of_place,
        :region,
        :lat,
        :long,
        story_ids: []
      )
    end
  end
end

rails/app/controllers/dashboard/search_controller.rb
module Dashboard
  class SearchController < BaseController
    def index
      @page = SearchPage.new(current_community, search_params)
      @results = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "results", formats: [:html]),
            pagination: @page.has_next_page? ? search_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    private

    def search_params
      params.permit(
        :search,
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/speakers_controller.rb
module Dashboard
  class SpeakersController < BaseController
    def index
      @page = SpeakersPage.new(community_speakers, meta_params)
      @speakers = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "speakers", formats: [:html]),
            pagination: @page.has_next_page? ? speakers_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    def new
      authorize @speaker = community_speakers.new
    end

    def create
      authorize Speaker
      @speaker = community_speakers.new(speaker_params)

      if @speaker.save
        redirect_to @speaker
      else
        render :new
      end
    end

    def show
      @speaker = authorize community_speakers.find(params[:id])
    end

    def edit
      @speaker = authorize community_speakers.find(params[:id])
    end

    def update
      @speaker = authorize community_speakers.find(params[:id])

      if @speaker.update(speaker_params)
        redirect_to @speaker
      else
        render :edit
      end
    end

    def destroy
      @speaker = authorize community_speakers.find(params[:id])

      @speaker.destroy

      redirect_to speakers_path
    end

    def delete_photo
      @speaker = authorize community_speakers.find(params[:speaker_id])
      @speaker.photo.purge

      head :ok
    end

    private

    def community_speakers
      policy_scope(current_community.speakers)
    end

    def speaker_params
      params.require(:speaker).permit(
        :name,
        :photo,
        :speaker_community,
        :birthdate,
        :birthplace_id,
        story_ids: []
      )
    end
  end
end

rails/app/controllers/dashboard/stories_controller.rb
module Dashboard
  class StoriesController < BaseController
    def index
      @page = StoriesPage.new(community_stories, filter_params)
      @stories = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "stories", formats: [:html]),
            pagination: @page.has_next_page? ? stories_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    def new
      authorize @story = community_stories.new
    end

    def create
      authorize Story

      if ActiveModel::Type::Boolean.new.cast(story_params[:story_pinned])
        community_stories.update_all(story_pinned: false)
      end

      @story = community_stories.new(story_params.except(:media))

      if @story.save
        story_params[:media]&.each do |media|
          m = @story.media.create(media: media)
        end
        redirect_to @story
      else
        render :new
      end
    end

    def show
      @story = authorize community_stories.find(params[:id])
    end

    def edit
      @story = authorize community_stories.find(params[:id])
    end

    def update
      @story = authorize community_stories.find(params[:id])

      if !@story.story_pinned && ActiveModel::Type::Boolean.new.cast(story_params[:story_pinned])
        community_stories.update_all(story_pinned: false)
      end

      if @story.update(story_params.except(:media))
        story_params[:media]&.each do |media|
          m = @story.media.create(media: media)
        end

        redirect_to @story
      else
        render :edit
      end
    end

    def pin
      @story = authorize community_stories.find(params[:id])
      community_stories.update_all(story_pinned: false)
      @story.update(story_pinned: true)

      redirect_to stories_path
    end

    def unpin
      @story = authorize community_stories.find(params[:id])
      @story.update(story_pinned: false)

      redirect_to stories_path
    end

    def destroy
      @story = authorize community_stories.find(params[:id])

      @story.destroy

      redirect_to stories_path
    end

    def delete_media
      @story = authorize community_stories.find(params[:story_id])

      media = @story.media.find(params[:id])
      media.destroy

      head :ok
    end

    private

    def community_stories
      policy_scope(current_community.stories)
    end

    def story_params
      params.require(:story).permit(
        :title,
        :desc,
        :date_interviewed,
        :language,
        :permission_level,
        :topic,
        :interview_location_id,
        :interviewer_id,
        :story_pinned,
        media: [],
        speaker_ids: [],
        place_ids: []
      )
    end

    def filter_params
      params.permit(
        :place,
        :speaker,
        :visibility,
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/themes_controller.rb
module Dashboard
  class ThemesController < BaseController
    def edit
      @theme = current_community.theme
    end

    def show
      redirect_to edit_theme_path
    end

    def update
      @theme = current_community.theme
      if @theme.update(theme_params)
        if current_community.public? && @community.theme.mapbox_token.present?
          static_map_url = if @theme.boundaries
            "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@theme.boundaries.flatten.to_s.gsub(' ','').sub("[", "%5B").sub("]", "%5D")}/900x600?access_token=#{@theme.mapbox_token}"
          else
            "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@theme.center_long},#{@theme.center_lat},#{@theme.zoom},#{@theme.bearing},#{@theme.pitch}/900x600?access_token=#{@theme.mapbox_token}"
          end
          begin
            @theme.static_map.attach(io: URI.parse(static_map_url).open, filename: "#{current_community.slug}-static-map.png")
          rescue StandardError
            # do nothing; no worries if we can't save the map
          end
        end
        redirect_to edit_theme_path
      else
        render :edit
      end
    end

    private

    def theme_params
      params.require(:theme).permit(
        :mapbox_style_url,
        :mapbox_access_token,
        :mapbox_3d,
        :protomaps_api_key,
        :protomaps_basemap_style,
        :center_lat,
        :center_long,
        :sw_boundary_lat,
        :sw_boundary_long,
        :ne_boundary_lat,
        :ne_boundary_long,
        :zoom,
        :pitch,
        :bearing,
        :map_projection,
        community_attributes: [
          :id,
          :background_img,
          sponsor_logos: []
        ]
      )
    end
  end
end

rails/app/views/dashboard/users/_users.html.erb
<% @users.each do |user| %>
  <%= link_to user, class: "card card--narrow card--center" do %>
    <% if user.photo.attached? %>
      <% if user.photo.variable? %>
        <%= image_tag user.photo.variant(resize_to_fill: [300, 300]), class: "card__img--circle", alt: user.display_name, title: user.display_name %>
      <% else %>
        <%= image_tag user.photo, class: "card__img--circle", alt: user.display_name, title: user.display_name %>
      <% end %>
    <% else %>
      <%= image_tag asset_path("speaker.png"), class: "card__img--circle", alt: user.display_name, title: user.display_name %>
    <% end %>
    <div class="card--wrap"><%= user.display_name %></div>
    <% if user.role %>
      <div class="badge"><%= User.human_attribute_name("role.#{user.role}") %></div>
    <% end %>
  <% end %>
<% end %>

rails/app/views/dashboard/users/edit.html.erb
<% content_for(:title) do %>
  <%= @user.display_name %> | <%= t("user") %>
<% end %>

<% content_for(:main_heading) do %>
  <div class="avatar-card">
    <span class="media-with-hover-controls rounded" data-replace-on-delete="<%= asset_path("speaker.png") %>">
      <% if @user.photo.attached? %>
        <% if @user.photo.variable? %>
          <%= image_tag @user.photo.variant(resize_to_fill: [300, 300]), alt: @user.display_name, title: @user.display_name  %>
        <% else %>
          <%= image_tag @user.photo, alt: @user.display_name, title: @user.display_name %>
        <% end %>
        <%= link_to user_photo_path(@user), class: "overlay delete-link", method: :delete, data: {confirm: t("dashboard.actions.confirm"), turbo_confirm: t("dashboard.actions.confirm"), turbo_method: :delete}, remote: true do %>
          <span><%= t("dashboard.actions.destroy") %></span>
        <% end %>
      <% else %>
        <%= image_tag asset_path("speaker.png"), alt: @user.display_name, title: @user.display_name %>
      <% end %>
    </span>
    <h2>
    <div class="small">
      <% if @user.name.present? %>
        <%= @user.username %> //
      <% end %>
      <%= @user.email %>
    </div>
    <%= @user.display_name %>
    <div class="small">
      <span class="badge"><%= User.human_attribute_name("role.#{@user.role}") %></span>
    </div>
  </h2>
  </div>
<% end %>

<%= form_with model: @user, multipart: true, class: "form aligned", id: "userForm", locale: true do |f| %>
  <%= render partial: "shared/form_errors", locals: { resource: @user } %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <% unless !((current_user.super_admin || current_user.admin?) && @user.id != current_user.id) %>
    <%= f.label :role %>
    <%= f.select :role, User.roles.keys.excluding('super_admin').map { |k| [User.human_attribute_name("role.#{k}"), k] } %>
  <% end %>

  <fieldset>
    <%= f.label :reset_password, for: :user_password %>
    <%= f.password_field :password %>
  </fieldset>

  <%= f.submit %>
<% end %>

rails/app/views/dashboard/users/index.html.erb
<% content_for(:title) do %>
  <%= t("users") %>
<% end %>

<% content_for(:main_heading) do %>
  <div class="columns">
    <h2><%= t("users") %></h2>
    <%= link_to t("dashboard.actions.new"), new_user_path, class: "btn" if policy(:user).new? %>
  </div>
<% end %>

<div class="infinite-scroll">
  <% if @users.empty? %>
    <p><%= t("list.no_results", resources: t("users").downcase) %></p>
  <% else %>
    <div data-infinite-scroll="entries" class="collection">
      <%= render "users" %>
    </div>
    <div data-infinite-scroll="pagination">
      <%#= Prev/Next Pagination Links for folks that don't use / have JavaScript %>
      <% if @page.meta[:offset] > 0 %>
        <%= link_to "Prev", users_path(request.query_parameters.merge(offset: @page.meta[:offset] - @page.meta[:limit])), rel: "prev" %>
      <% end %>
      <% if @page.meta[:next_offset] %>
        <%= link_to "Next", users_path(request.query_parameters.merge(offset: @page.meta[:next_offset])), rel: "next" %>
      <% end %>
    </div>
  <% end %>
</div>

rails/app/views/dashboard/users/new.html.erb
<% content_for(:title) do %>
  <%= t("dashboard.headings.new_resource", name: t("user")) %>
<% end %>

<% content_for(:main_heading) do %>
<h2><%= t("dashboard.headings.new_resource", name: t("user")) %></h2>
<% end %>

<%= form_with model: @user, multipart: true, class: "form aligned", id: "userForm", locale: true do |f| %>
  <%= render partial: "shared/form_errors", locals: { resource: @user } %>

  <%= f.label :username, class: "required" %>
  <%= f.text_field :username, required: true %>

  <%= f.label :password, class: "required" %>
  <%= f.password_field :password, required: true %>

  <%= f.label :role, class: "required" %>
  <%= f.select :role, User.roles.keys.excluding('super_admin').map { |k| [User.human_attribute_name("role.#{k}"), k] } %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :photo %>
  <%= f.file_field :photo %>

  <%= f.submit %>
<% end %>

rails/app/views/dashboard/users/show.html.erb
<% content_for(:title) do %>
  <%= @user.display_name %> | <%= t("user") %>
<% end %>

<% content_for(:main_heading) do %>
<div class="columns">
  <div class="avatar-card">
  <% if @user.photo.attached? %>
    <% if @user.photo.variable? %>
      <%= image_tag @user.photo.variant(resize_to_fill: [300, 300]), class: "img--rounded img--mega", alt: @user.display_name, title: @user.display_name %>
    <% else %>
      <%= image_tag @user.photo, class: "img--rounded img--mega", alt: @user.display_name, title: @user.display_name %>
    <% end %>
  <% else %>
    <%= image_tag asset_path("speaker.png"), class: "img--rounded img--mega", alt: @user.display_name, title: @user.display_name %>
  <% end %>
  <h2>
    <div class="small">
      <% if @user.name.present? %>
        <%= @user.username %> //
      <% end %>
      <%= @user.email %>
    </div>
    <%= @user.display_name %>
    <div class="small">
      <span class="badge"><%= User.human_attribute_name("role.#{@user.role}") %></span>
    </div>
  </h2>
  </div>
  <div>
    <%= link_to t("dashboard.actions.edit"), edit_user_path(@user), class: "btn" if policy(@user).edit? %>
    <%= link_to t("dashboard.actions.destroy"), user_path(@user), method: :delete, data: {confirm: t("dashboard.actions.confirm"), turbo_confirm: t("dashboard.actions.confirm"), turbo_method: :delete}, class: "btn btn-danger" if policy(@user).destroy? %>
  </div>
</div>
<% end %>