rails/config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :communities, only: [:index, :show] do
      resources :stories, only: [:index, :show]
      resources :places, only: [:show]
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    scope '/member', module: 'dashboard', constraints: RoleRoutingConstraint.new { |user| !user.super_admin } do
      root to: "stories#index", as: :member_root

      get :search, to: "search#index"

      resource :community, only: [:show, :update], as: :community_settings do
        delete :background_img, action: :delete_background_img
        delete :display_image, action: :delete_display_image
        delete '/sponsor_logo/:id/delete', action: :delete_sponsor_logo, as: :delete_sponsor_logo
      end
      resources :users do
        delete :photo, action: :delete_photo
      end
      resources :speakers do
        delete :photo, action: :delete_photo
      end
      resources :places do
        delete :photo, action: :delete_photo
        delete :name_audio, action: :delete_name_audio
      end
      resources :stories do
        delete '/media/:id/delete', action: :delete_media, as: :delete_media
      end
      resource :theme, only: [:update, :edit, :show]
      resource :import, only: [:show, :create] do
        post :preview
      end
    end

    # super admin resource routes
    scope '/admin', module: 'super_admin', constraints: RoleRoutingConstraint.new { |user| user.super_admin } do
      root to: "metrics#show", as: :super_admin_root

      resource :metrics, only: :show
      resources :communities
      resources :features do
        post :enable
        post :disable
      end
    end

    get :login, to: "sessions#new"
    post :login, to: "sessions#create"
    delete :logout, to: "sessions#destroy"

    get :profile, to: "profile#edit"
    patch :profile, to: "profile#update"
    get :change_password, to: "passwords#edit"
    post :change_password, to: "passwords#update"

    root to: 'welcome#index'
    get 'home', to: 'home#index', as: "home_map"
    get "search", to: "home#community_search_index", as: "community_search"

    get :onboard, to: "onboard#start", as: :start_onboarding
    namespace :onboard do
      resource :community, controller: :community, only: [:show, :create], as: :community
      resource :account, controller: :account, only: [:show, :create], as: :admin_account
    end
  end
end

rails/app/models/community.rb
class Community < ApplicationRecord
  has_one_attached :display_image
  has_one_attached :background_img
  has_many_attached :sponsor_logos

  has_many :users, dependent: :nullify
  has_many :places, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :speakers, dependent: :destroy

  has_one :theme, dependent: :destroy

  after_create :create_theme, if: -> { theme.nil? }

  accepts_nested_attributes_for :users, limit: 1

  validates :background_img, content_type: [:png, :jpeg], size: { less_than_or_equal_to: 5.megabytes }
  validates :sponsor_logos, content_type: [:png, :jpeg], size: { less_than_or_equal_to: 5.megabytes }

  validates :slug, presence: true, if: -> { self.public? }

  FILTERABLE_ATTRIBUTES = %w(places region type_of_place speakers topic language speaker_community)

  # override(slug)
  # ensure slug is set using downcased and underscored name
  # ensure slug value is unique by appending idx when necessary
  def slug=(value)
    value = self.name.downcase.strip.gsub(" ", "_") if value.blank?
    if Community.where.not(id: self).exists?(slug: value)
      index = value.split("_").last.to_i
      loop do
        index+=1
        value = [value, index].join("_")
        break unless Community.exists?(slug: value)
      end
    end
    super(value)
  end

  def filters(permission_level = :anonymous)
    [
      places.joins(:stories).where(stories: {permission_level: permission_level}).distinct.map { |p| {label: p.name, value: p.id, category: :places } },
      places.joins(:stories).where(stories: {permission_level: permission_level}).pluck(:region).uniq.reject(&:blank?).map { |r| {label: r, value: r, category: :region } },
      places.joins(:stories).where(stories: {permission_level: permission_level}).pluck(:type_of_place).uniq.reject(&:blank?).map { |r| {label: r, value: r, category: :type_of_place } },
      stories.where(stories: {permission_level: permission_level}).pluck(:topic).uniq.reject(&:blank?).map { |r| {label: r, value: r, category: :topic } },
      stories.where(stories: {permission_level: permission_level}).pluck(:language).uniq.reject(&:blank?).map { |r| {label: r, value: r, category: :language } },
      speakers.joins(:stories).where(stories: {permission_level: permission_level}).distinct.map { |s| {value: s.id, label: s.name, category: :speakers } },
      speakers.joins(:stories).where(stories: {permission_level: permission_level}).pluck(:speaker_community).uniq.reject(&:blank?).map { |r| {label: r, value: r, category: :speaker_community } }
    ].flatten
  end

  # Flipper Feature Groups
  # See config/initializers/flipper.rb to view registered groups
  def feature_groups
    Flipper.groups.each_with_object([]) do |group, arr|
      arr << group.name if self.respond_to?(group.name) ? self.send(group.name) : self.send("#{group.name}_group?")
    end
  end

  # Flipper `developers` group conditions
  def developers_group?
    name.match?("Ruby for Good")
  end
end

# == Schema Information
#
# Table name: communities
#
#  id          :bigint           not null, primary key
#  beta        :boolean          default(FALSE)
#  country     :string
#  description :text
#  locale      :string
#  name        :string
#  public      :boolean          default(FALSE), not null
#  slug        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_communities_on_public  (public)
#  index_communities_on_slug    (slug)
#

rails/app/controllers/api/stories_controller.rb
module Api
  class StoriesController < BaseController
    def index
      community = Community.where(public: true).find_by!(slug: params[:community_id])
      @page = Api::StoriesPage.new(community, story_params)

      @stories = @page.data
    end

    def show
      community = Community.where(public: true).find_by!(slug: params[:community_id])
      @story = community.stories.where(permission_level: :anonymous).preload(:places, :speakers).find(params[:id])
    end

    private

    def story_params
      params.permit(
        :sort_by,
        :sort_dir,
        :limit,
        :offset,
        places: [],
        region: [],
        topic: [],
        type_of_place: [],
        language: [],
        speakers: [],
        speaker_community: [],
      )
    end
  end
end

rails/app/controllers/dashboard/application_controller.rb
module Dashboard
  class ApplicationController < ApplicationController
    rescue_from Pundit::NotAuthorizedError, with: :not_authorized
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    layout "dashboard"

    before_action :authenticate_user!

    protected

    def not_authorized
      flash.alert = "You are not authorized to perform this action"
      redirect_to member_root_path
    end

    def not_found
      flash.alert = "The resource you requested cannot be found"
      redirect_to member_root_path
    end

    private

    def meta_params
      params.permit(
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    rescue_from Pundit::NotAuthorizedError, with: :not_authorized
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    layout "dashboard"

    before_action :authenticate_user!

    protected

    def not_authorized
      flash.alert = "You are not authorized to perform this action"
      redirect_to member_root_path
    end

    def not_found
      flash.alert = "The resource you requested cannot be found"
      redirect_to member_root_path
    end

    private

    def meta_params
      params.permit(
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/communities_controller.rb
module Dashboard
  class CommunitiesController < BaseController
    def show
      @community = authorize current_user.community
    end

    def update
      @community = authorize current_user.community

      @community.update(community_params)

      # Append new sponsor logos
      if file_uploads.present?
        file_uploads[:sponsor_logos].each do |logo|
          @community.sponsor_logos.attach(io: logo, filename: logo.original_filename)
        end
      end

      if @community.public? && @community.theme.mapbox_token.present?
        static_map_url = if @community.theme.boundaries
          "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@community.theme.boundaries.flatten.to_s.gsub(' ','').sub("[", "%5B").sub("]", "%5D")}/900x600?access_token=#{@community.theme.mapbox_token}"
        else
          "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@community.theme.center_long},#{@community.theme.center_lat},#{@community.theme.zoom},#{@community.theme.bearing},#{@community.theme.pitch}/900x600?access_token=#{@community.theme.mapbox_token}"
        end
        begin
          @community.theme.static_map.attach(io: URI.open(static_map_url), filename: "#{@community.slug}-static-map.png")
        rescue StandardError
          # do nothing; no worries if we can't save the map
        end
      end

      redirect_to community_settings_path
    end

    def delete_background_img
      @community = authorize current_user.community, :delete_attachments?
      @community.background_img.purge

      head :ok
    end

    def delete_display_image
      @community = authorize current_user.community, :delete_attachments?
      @community.display_image.purge

      head :ok
    end

    def delete_sponsor_logo
      @community = authorize current_user.community, :delete_attachments?
      logo_blob = @community.sponsor_logos.blobs.find_signed(params[:id])
      logo_blob.attachments.each(&:purge)

      head :ok
    end

    private

    def community_params
      params.require(:community).permit(
        :beta,
        :public,
        :background_img,
        :display_image,
        :description
      )
    end

    def file_uploads
      params.require(:community).permit(sponsor_logos: [])
    end
  end
end

rails/app/controllers/dashboard/imports_controller.rb
module Dashboard
  class ImportsController < BaseController
    rescue_from Importable::FileImporter::HeaderMismatchError, with: :mapped_header_mismatch
    def show

    end

    def preview
      @model = params[:model]
      @required_headers = @model.classify.constantize&.csv_headers
      @csv = CSV.open(params[:file], headers: true) { |csv| csv.first.headers }

      render json: {
        headers: render_to_string(partial: "header_matches", formats: [:html])
      }
    end

    def create
      places_file = import_params[:places_csv]
      place_result = if places_file.present?
        place_headers = import_params[:place_headers].to_h
        Place.import(places_file, current_community.id, place_headers)
      end

      speakers_file = params[:speakers_csv]
      speaker_result = if speakers_file.present?
        speaker_headers = import_params[:speaker_headers].to_h
        Speaker.import(speakers_file, current_community.id, speaker_headers)
      end

      stories_file = params[:stories_csv]
      story_result = if stories_file.present?
        story_headers = import_params[:story_headers].to_h
        Story.import(stories_file, current_community.id, story_headers)
      end

      render locals: {
        places: place_result,
        speakers: speaker_result,
        stories: story_result
      }
    end

    private

    def import_params
      params.permit(
        :places_csv,
        :speakers_csv,
        :stories_csv,
        place_headers: Place.csv_headers,
        speaker_headers: Speaker.csv_headers,
        story_headers: Story.csv_headers
      )
    end

    def mapped_header_mismatch
      flash.alert = "Additional headers detected. Please verify your CSV headers against the resource you are importing."
      redirect_to import_path
    end
  end
end

rails/app/controllers/dashboard/places_controller.rb
module Dashboard
  class PlacesController < BaseController
    def index
      @page = PlacesPage.new(community_places, meta_params)
      @places = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "places", formats: [:html]),
            pagination: @page.has_next_page? ? places_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    def new
      # set initial position using the current community's theme
      current_theme = current_community.theme
      authorize @place = community_places.new(lat: current_theme.center_lat || 0, long: current_theme.center_long || 0)
    end

    def create
      authorize Place
      @place = community_places.new(place_params)

      if @place.save
        redirect_to @place
      else
        render :new
      end
    end

    def show
      @place = authorize community_places.find(params[:id])
    end

    def edit
      @place = authorize community_places.find(params[:id])
    end

    def update
      @place = authorize community_places.find(params[:id])

      if @place.update(place_params)
        redirect_to @place
      else
        render :edit
      end
    end

    def destroy
      @place = authorize community_places.find(params[:id])

      @place.destroy

      redirect_to places_path
    end

    def delete_photo
      @place = authorize community_places.find(params[:place_id])
      @place.photo.purge

      head :ok
    end

    def delete_name_audio
      @place = authorize community_places.find(params[:place_id])
      @place.name_audio.purge

      head :ok
    end

    private

    def community_places
      policy_scope(current_community.places)
    end

    def place_params
      params.require(:place).permit(
        :name,
        :description,
        :photo,
        :name_audio,
        :type_of_place,
        :region,
        :lat,
        :long,
        story_ids: []
      )
    end
  end
end

rails/app/controllers/dashboard/search_controller.rb
module Dashboard
  class SearchController < BaseController
    def index
      @page = SearchPage.new(current_community, search_params)
      @results = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "results", formats: [:html]),
            pagination: @page.has_next_page? ? search_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    private

    def search_params
      params.permit(
        :search,
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/speakers_controller.rb
module Dashboard
  class SpeakersController < BaseController
    def index
      @page = SpeakersPage.new(community_speakers, meta_params)
      @speakers = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "speakers", formats: [:html]),
            pagination: @page.has_next_page? ? speakers_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    def new
      authorize @speaker = community_speakers.new
    end

    def create
      authorize Speaker
      @speaker = community_speakers.new(speaker_params)

      if @speaker.save
        redirect_to @speaker
      else
        render :new
      end
    end

    def show
      @speaker = authorize community_speakers.find(params[:id])
    end

    def edit
      @speaker = authorize community_speakers.find(params[:id])
    end

    def update
      @speaker = authorize community_speakers.find(params[:id])

      if @speaker.update(speaker_params)
        redirect_to @speaker
      else
        render :edit
      end
    end

    def destroy
      @speaker = authorize community_speakers.find(params[:id])

      @speaker.destroy

      redirect_to speakers_path
    end

    def delete_photo
      @speaker = authorize community_speakers.find(params[:speaker_id])
      @speaker.photo.purge

      head :ok
    end

    private

    def community_speakers
      policy_scope(current_community.speakers)
    end

    def speaker_params
      params.require(:speaker).permit(
        :name,
        :photo,
        :speaker_community,
        :birthdate,
        :birthplace_id,
        story_ids: []
      )
    end
  end
end

rails/app/views/dashboard/stories/_form.html.erb
<%= form_with model: @story, multipart: true, class: "form", locale: true do |f| %>
  <%= render partial: "shared/form_errors", locals: { resource: @story } %>

  <%= f.label :title, class: "required" %>
  <%= f.text_field :title, required: true %>

  <%= f.label :desc %>
  <%= f.text_area :desc, rows: 3 %>

  <%= f.label :language %>
  <%= f.text_field :language %>

  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <%= f.label :date_interviewed %>
  <%= f.date_field :date_interviewed %>

  <%= f.label :media %>
  <%= f.file_field :media, multiple: true %>

  <% if @story.persisted? %>
  <div class="with-media-list">
    <% if @story.media.any? %>
      <% @story.media.each do |media| %>
        <span class="media-with-controls">
          <%= render partial: "media", locals: {media: media.media, size: 150} %>
          <%= link_to t("dashboard.actions.destroy"), story_delete_media_path(@story, media.id), class: "delete-link", method: :delete, data: {confirm: t("dashboard.actions.confirm"), turbo_confirm: t("dashboard.actions.confirm"), turbo_method: :delete}, remote: true %>
        </span>
      <% end %>
    <% end %>
  </div>
  <% end %>

  <%= f.label :speaker_ids, class: "required" %>
  <div class="checklist">
    <%= f.collection_check_boxes :speaker_ids, current_community.speakers, :id, :name, required: true %>
  </div>

  <%= f.label :place_ids, class: "required" %>
  <div class="checklist">
    <%= f.collection_check_boxes :place_ids, current_community.places, :id, :name, required: true %>
  </div>

  <%= f.label :interview_location_id %>
  <%= f.collection_select :interview_location_id, current_community.places, :id, :name, include_blank: true %>

  <%= f.label :interviewer_id %>
  <%= f.collection_select :interviewer_id, current_community.speakers, :id, :name, include_blank: true %>

  <%= f.label :permission_level %>
  <%= f.select :permission_level, Story.permission_levels.keys.map { |k| [Story.human_attribute_name("permission_level.#{k}"), k]} %>

  <%= f.submit %>
<% end %>

rails/app/views/dashboard/stories/_media.html.erb
<% if media.image? %>
  <% if media.variable? %>
    <%= image_tag(media.variant(resize_to_limit: [size, size])) %>
  <% else %>
    <%= image_tag(media, width: size) %>
  <% end %>
<% elsif media.video? %>
  <video
    controls
    disablePictureInPicture
    controlsList="nodownload"
    id="video-player-<%= media.blob.id %>"
    poster="<%= url_for(media.preview(resize_to_limit:[nil, size])) if media.previewable? %>"
  >
    <source src="<%= url_for(media) %>"/>
    <%= t("video_unsupported") %>
  </video>
<% elsif media.audio? %>
  <audio id="audio-player-<%= media.blob.id %>"
    controls
    controlsList="nodownload"
    ref="audio"
  >
    <source src="<%= url_for(media) %>" type="<%= media.blob.content_type %>" />
  </audio>
<% elsif media.previewable? %>
  <%= image_tag(media.preview(resize_to_limit:[size, size])) %>
<% else %>
  <%= media.filename %>
<% end %>

rails/app/views/dashboard/stories/_stories.erb
<% @stories.each do |story| %>
  <%= link_to story, class: "card" do %>
    <div>
      <h3>
        <span class="card__heading--small"><%= story.topic %></span>
        <%= story.title %>
      </h3>

      <% if story.language.present? %>
        <span class="badge badge-red"><%= story.language %></span>
      <% end %>

      <% if story.permission_level.present? %>
        <span class="badge badge-green"><%= Story.human_attribute_name("permission_level.#{story.permission_level}") %></span>
      <% end %>

    <p><%= story.desc %></p>
    </div>

    <div>
      <span>
        <% if story.places.any? %>
        <svg class="icon">
          <use href="#icon-location-pin">
        </svg>
        <%= story.places.map(&:name).join(", ") %>
        <% end %>
      </span>
      <div class="avatars">
        <% story.speakers.each do |speaker| %>
          <span class="tooltip">
            <% if speaker.photo.attached? %>
              <%= image_tag speaker.photo, class: "img--rounded img--mini", alt: speaker.name, title: speaker.name %>
            <% else %>
              <%= image_tag asset_path("speaker.png"), class: "img--rounded img--mini", alt: speaker.name, title: speaker.name %>
            <% end %>

            <span class="tooltip-text"><%= speaker.name %></span>
          </span>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

rails/app/views/dashboard/stories/edit.html.erb
<% content_for(:title) do %>
  <%= @story.title %> | <%= t("story") %>
<% end %>

<% content_for(:main_heading) do %>
  <h2>
    <% if @story.topic.present? %>
      <div class="small"><%= @story.topic %></div>
    <% end %>
    <%= @story.title %>
    <div class="small">
      <% if @story.language.present? %>
        <span class="badge"><%= @story.language %></span>
      <% end %>

      <% if @story.permission_level.present? %>
        <span class="badge"><%= Story.human_attribute_name("permission_level.#{@story.permission_level}") %></span>
      <% end %>
    </div>
  </h2>
<% end %>

<%= render "form" %>

rails/app/views/dashboard/stories/index.html.erb
<% content_for(:title) do %>
  <%= t("stories") %>
<% end %>

<% content_for(:main_heading) do %>
  <div class="columns">
  <h2><%= t("stories") %></h2>
  <%= link_to t("dashboard.actions.new"), new_story_path, class: "btn" if policy(:story).new? %>
  </div>
  <%= form_with url: stories_path, method: :get, class: "filters", local: true do |f| %>
    <div>
    <%= f.label :place, t("place") %>
    <%= f.collection_select :place, current_community.places, :id, :name, include_blank: t("filter.all"), selected: params[:place] %>
    </div>
    <div>
    <%= f.label :speaker, t("speaker") %>
    <%= f.collection_select :speaker, current_community.speakers, :id, :name, include_blank: t("filter.all"), selected: params[:speaker] %>
    </div>
    <% unless current_user.viewer? %>
      <div>
      <%= f.label :visibility %>
      <%= f.select :visibility, Story.permission_levels.map { |k, v| [Story.human_attribute_name("permission_level.#{k}"), v]}, include_blank: t("filter.any"), selected: params[:visibility] %>
      </div>
    <% end %>
    <%= f.submit t("filter.label"), name: nil, class: "filter" %>
  <% end %>
<% end %>

<div class="infinite-scroll">
  <% if @stories.empty? %>
    <p><%= t("list.no_results", resources: t("stories").downcase) %></p>
  <% else %>
    <div data-infinite-scroll="entries" class="collection">
    <%= render "stories" %>
    </div>
    <div data-infinite-scroll="pagination">
      <%#= Prev/Next Pagination Links for folks that don't use / have JavaScript %>
      <% if @page.meta[:offset] > 0 %>
        <%= link_to t("list.prev"), stories_url(request.query_parameters.merge(offset: @page.meta[:offset] - @page.meta[:limit])), rel: "prev" %>
      <% end %>
      <% if @page.meta[:next_offset] %>
        <%= link_to t("list.next"), stories_url(request.query_parameters.merge(offset: @page.meta[:next_offset])), rel: "next" %>
      <% end %>
    </div>
  <% end %>
</div>

rails/app/views/dashboard/stories/new.html.erb
<% content_for(:title) do %>
  <%= t("dashboard.headings.new_resource", name: t("story")) %>
<% end %>

<% content_for(:main_heading) do %>
  <h2><%= t("dashboard.headings.new_resource", name: t("story")) %></h2>
<% end %>

<%= render "form" %>

rails/app/views/dashboard/stories/show.html.erb
<% content_for(:title) do %>
  <%= @story.title %> | <%= t("story") %>
<% end %>

<% content_for(:main_heading) do %>
<div class="columns">
  <h2>
    <% if @story.topic.present? %>
      <div class="small"><%= @story.topic %></div>
    <% end %>
    <%= @story.title %>
    <div class="small">
      <% if @story.language.present? %>
        <span class="badge badge-red"><%= @story.language %></span>
      <% end %>

      <% if @story.permission_level.present? %>
        <span class="badge badge-green"><%= Story.human_attribute_name("permission_level.#{@story.permission_level}") %></span>
      <% end %>
    </div>
  </h2>
  <div class="actions">
    <%= link_to t("dashboard.actions.edit"), edit_story_path(@story), class: "btn" if policy(@story).edit? %>
    <%= link_to t("dashboard.actions.destroy"), story_path(@story), method: :delete, data: {confirm: t("dashboard.actions.confirm"), turbo_confirm: t("dashboard.actions.confirm"), turbo_method: :delete}, class: "btn btn-danger" if policy(@story).destroy? %>
  </div>
</div>
<% end %>

<div class="two-columns">
  <div class="two-columns-right column-fixed-350">
    <% if @story.places.any? %>
      <section>
        <div id="static-map"></div>
        <% @story.places.each do |place| %>
          <p>
            <span class="badge badge-blue"><%= place.name[0].upcase %></span>
            <%= place.name %>
          </p>
          <p>
            <% if place.region.present? %>
              <%= place.region %>
            <% end %>
            <% if place.type_of_place.present? %><span class="badge"><%= place.type_of_place %></span><% end %>
          </p>
        <% end %>
      </section>
    <% end %>

    <section class="collection">
      <% if @story.interviewer %>
        <span class="card card--mini card--center card--noborder card--nogap">
          <% if @story.interviewer.photo.attached? %>
            <% if @story.interviewer.photo.variable? %>
              <%= image_tag  @story.interviewer.photo.variant(resize_to_fill: [300, 300]), class: "img--rounded img--large", alt: @story.interviewer.name, title: @story.interviewer.name %>
            <% else %>
              <%= image_tag  @story.interviewer.photo, class: "img--rounded img--large", alt: @story.interviewer.name, title: @story.interviewer.name %>
            <% end %>
          <% else %>
            <%= image_tag asset_path("speaker.png"), class: "img--rounded img--large", alt: @story.interviewer.name, title: @story.interviewer.name %>
          <% end %>

          <div><%= @story.interviewer.name %></div>
          <div class="small"><%= t("interviewer") %></div>
        </span>
      <% end %>
      <% policy_scope(@story.speakers).each do |speaker| %>
        <span class="card card--mini card--center card--noborder card--nogap">
          <% if speaker.photo.attached? %>
            <% if speaker.photo.variable? %>
              <%= image_tag speaker.photo.variant(resize_to_fill: [300, 300]), class: "img--rounded img--large", alt: speaker.name, title: speaker.name %>
            <% else %>
              <%= image_tag speaker.photo, class: "img--rounded img--large", alt: speaker.name, title: speaker.name %>
            <% end %>
          <% else %>
            <%= image_tag asset_path("speaker.png"), class: "img--rounded img--large", alt: speaker.name, title: speaker.name %>
          <% end %>

          <div><%= speaker.name %></div>
          <div class="small"><%= t("speaker") %></div>
        </span>
      <% end %>
    </section>
  </div>

  <div class="two-columns-left">
    <p class="render-lines"><%= sanitize @story.desc, tags: %w(strong em u) %></p>

    <% @story.media.each do |media| %>
      <p class="media">
        <%= render partial: "media", locals: {media: media.media, size: 400} %>
      </p>
    <% end %>
  </div>
</div>

<script>
Terrastories.map_utils.staticMap(
  <%= current_community.theme.use_maplibre? %>,
  {
    accessToken: "<%= current_community.theme.mapbox_token %>",
    container: "static-map", // container ID
    zoom: <%= current_community.theme.zoom %>,
    style: "<%= current_community.theme.map_style_url %>", // style URL or style object
    basemapStyle: "<%= current_community.theme.basemap_style %>",
    allowDrag: true,
  },
  <%= raw @story.static_map_markers %>
)
</script>