rails/config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :communities, only: [:index, :show] do
      resources :stories, only: [:index, :show]
      resources :places, only: [:show]
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    scope '/member', module: 'dashboard', constraints: RoleRoutingConstraint.new { |user| !user.super_admin } do
      root to: "stories#index", as: :member_root

      get :search, to: "search#index"

      resource :community, only: [:show, :update], as: :community_settings do
        delete :background_img, action: :delete_background_img
        delete :display_image, action: :delete_display_image
        delete '/sponsor_logo/:id/delete', action: :delete_sponsor_logo, as: :delete_sponsor_logo
      end
      resources :users do
        delete :photo, action: :delete_photo
      end
      resources :speakers do
        delete :photo, action: :delete_photo
      end
      resources :places do
        delete :photo, action: :delete_photo
        delete :name_audio, action: :delete_name_audio
      end
      resources :stories do
        delete '/media/:id/delete', action: :delete_media, as: :delete_media
      end
      resource :theme, only: [:update, :edit, :show]
      resource :import, only: [:show, :create] do
        post :preview
      end
    end

    # super admin resource routes
    scope '/admin', module: 'super_admin', constraints: RoleRoutingConstraint.new { |user| user.super_admin } do
      root to: "metrics#show", as: :super_admin_root

      resource :metrics, only: :show
      resources :communities
      resources :features do
        post :enable
        post :disable
      end
    end

    get :login, to: "sessions#new"
    post :login, to: "sessions#create"
    delete :logout, to: "sessions#destroy"

    get :profile, to: "profile#edit"
    patch :profile, to: "profile#update"
    get :change_password, to: "passwords#edit"
    post :change_password, to: "passwords#update"

    root to: 'welcome#index'
    get 'home', to: 'home#index', as: "home_map"
    get "search", to: "home#community_search_index", as: "community_search"

    get :onboard, to: "onboard#start", as: :start_onboarding
    namespace :onboard do
      resource :community, controller: :community, only: [:show, :create], as: :community
      resource :account, controller: :account, only: [:show, :create], as: :admin_account
    end
  end
end

rails/app/models/place.rb
class Place < ApplicationRecord
  include Importable

  belongs_to :community, touch: true
  has_and_belongs_to_many :stories
  has_one_attached :photo
  has_one_attached :name_audio
  validates :name, presence: true
  validates :photo, content_type: [:png, :jpeg], size: { less_than_or_equal_to: 5.megabytes }
  validates :name_audio,
    content_type: [
      :mp3, :aac, :flac, :mp4a, :wav,
      'audio/wav', 'audio/m4a', 'audio/x-m4a', 'audio/x-aac', 'audio/x-flac',
    ],
    size: { less_than_or_equal_to: 10.megabytes }
  validates :lat, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90, message: :invalid_latitude }, allow_blank: true
  validates :long, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180, message: :invalid_longitude}, allow_blank: true
  has_many :interview_stories, class_name: "Story", foreign_key: "interview_location_id"

  attr_reader :point_geojson

  scope :with_valid_coordinates, -> do
    where.not(lat: nil, long: nil)
  end

  def photo_url(full_url: false, thumbnail: false)
    if photo.attached?
      if full_url
        resize_limit = thumbnail ? [300, 300] : [800, 800]
        Rails.application.routes.url_helpers.rails_representation_url(photo.variant(resize_to_limit: resize_limit))
      else
        Rails.application.routes.url_helpers.rails_blob_path(photo)
      end
    end
  end

  def name_audio_url(full_url: false)
    if name_audio.attached?
      if full_url
        Rails.application.routes.url_helpers.rails_blob_url(name_audio)
      else
        Rails.application.routes.url_helpers.rails_blob_path(name_audio)
      end
    end
  end

  def point_geojson
    RGeo::GeoJSON.encode geojson
  end

  def self.export_sample_csv
    headers = %w{ name type_of_place description region long lat media }

    CSV.generate(headers: true) do |csv|
      csv << headers
    end
  end

  def static_map_markers
    geo = RGeo::GeoJSON.encode(
      RGeo::GeoJSON::Feature.new(
        RGeo::Cartesian.factory.point(long, lat),
        id,
        "marker-symbol": name[0]&.downcase || "P"
      )
    ).to_json
  end

  # keys are camelCased for Public Communities React FrontEnd
  def public_point_feature
    RGeo::GeoJSON.encode(
      RGeo::GeoJSON::Feature.new(
        RGeo::Cartesian.factory.point(long, lat),
        id,
        name: name,
        description: description,
        placenameAudio: name_audio_url(full_url: true),
        photo: photo_url(full_url: true),
        thumbnail: photo_url(full_url: true, thumbnail: true),
        region: region,
        typeOfPlace: type_of_place,
      )
    )
  end

  EXCLUDE_ATTRIBUTES_FROM_IMPORT = %i[
    stories
    interview_stories
  ]

  private

  def geojson
    # todo: add extra data here to pass to map about points
    RGeo::GeoJSON::Feature.new(
      RGeo::Cartesian.factory.point(long, lat),
      id,
      name: name,
      description: description,
      region: region,
      type_of_place: type_of_place,
      photo_url: photo_url,
      name_audio_url: name_audio_url,
      stories: stories
    )
  end

end

# == Schema Information
#
# Table name: places
#
#  id            :bigint           not null, primary key
#  description   :string
#  lat           :decimal(10, 6)
#  long          :decimal(10, 6)
#  name          :string
#  region        :string
#  type_of_place :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  community_id  :integer
#

rails/app/controllers/api/places_controller.rb
module Api
  class PlacesController < BaseController
    def show
      community = Community.where(public: true).find_by!(slug: params[:community_id])
      @place = community.places.find(params[:id])
    end
  end
end

rails/app/controllers/dashboard/application_controller.rb
module Dashboard
  class ApplicationController < ApplicationController
    rescue_from Pundit::NotAuthorizedError, with: :not_authorized
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    layout "dashboard"

    before_action :authenticate_user!

    protected

    def not_authorized
      flash.alert = "You are not authorized to perform this action"
      redirect_to member_root_path
    end

    def not_found
      flash.alert = "The resource you requested cannot be found"
      redirect_to member_root_path
    end

    private

    def meta_params
      params.permit(
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    rescue_from Pundit::NotAuthorizedError, with: :not_authorized
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    layout "dashboard"

    before_action :authenticate_user!

    protected

    def not_authorized
      flash.alert = "You are not authorized to perform this action"
      redirect_to member_root_path
    end

    def not_found
      flash.alert = "The resource you requested cannot be found"
      redirect_to member_root_path
    end

    private

    def meta_params
      params.permit(
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/communities_controller.rb
module Dashboard
  class CommunitiesController < BaseController
    def show
      @community = authorize current_user.community
    end

    def update
      @community = authorize current_user.community

      @community.update(community_params)

      # Append new sponsor logos
      if file_uploads.present?
        file_uploads[:sponsor_logos].each do |logo|
          @community.sponsor_logos.attach(io: logo, filename: logo.original_filename)
        end
      end

      if @community.public? && @community.theme.mapbox_token.present?
        static_map_url = if @community.theme.boundaries
          "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@community.theme.boundaries.flatten.to_s.gsub(' ','').sub("[", "%5B").sub("]", "%5D")}/900x600?access_token=#{@community.theme.mapbox_token}"
        else
          "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/#{@community.theme.center_long},#{@community.theme.center_lat},#{@community.theme.zoom},#{@community.theme.bearing},#{@community.theme.pitch}/900x600?access_token=#{@community.theme.mapbox_token}"
        end
        begin
          @community.theme.static_map.attach(io: URI.open(static_map_url), filename: "#{@community.slug}-static-map.png")
        rescue StandardError
          # do nothing; no worries if we can't save the map
        end
      end

      redirect_to community_settings_path
    end

    def delete_background_img
      @community = authorize current_user.community, :delete_attachments?
      @community.background_img.purge

      head :ok
    end

    def delete_display_image
      @community = authorize current_user.community, :delete_attachments?
      @community.display_image.purge

      head :ok
    end

    def delete_sponsor_logo
      @community = authorize current_user.community, :delete_attachments?
      logo_blob = @community.sponsor_logos.blobs.find_signed(params[:id])
      logo_blob.attachments.each(&:purge)

      head :ok
    end

    private

    def community_params
      params.require(:community).permit(
        :beta,
        :public,
        :background_img,
        :display_image,
        :description
      )
    end

    def file_uploads
      params.require(:community).permit(sponsor_logos: [])
    end
  end
end

rails/app/controllers/dashboard/imports_controller.rb
module Dashboard
  class ImportsController < BaseController
    rescue_from Importable::FileImporter::HeaderMismatchError, with: :mapped_header_mismatch
    def show

    end

    def preview
      @model = params[:model]
      @required_headers = @model.classify.constantize&.csv_headers
      @csv = CSV.open(params[:file], headers: true) { |csv| csv.first.headers }

      render json: {
        headers: render_to_string(partial: "header_matches", formats: [:html])
      }
    end

    def create
      places_file = import_params[:places_csv]
      place_result = if places_file.present?
        place_headers = import_params[:place_headers].to_h
        Place.import(places_file, current_community.id, place_headers)
      end

      speakers_file = params[:speakers_csv]
      speaker_result = if speakers_file.present?
        speaker_headers = import_params[:speaker_headers].to_h
        Speaker.import(speakers_file, current_community.id, speaker_headers)
      end

      stories_file = params[:stories_csv]
      story_result = if stories_file.present?
        story_headers = import_params[:story_headers].to_h
        Story.import(stories_file, current_community.id, story_headers)
      end

      render locals: {
        places: place_result,
        speakers: speaker_result,
        stories: story_result
      }
    end

    private

    def import_params
      params.permit(
        :places_csv,
        :speakers_csv,
        :stories_csv,
        place_headers: Place.csv_headers,
        speaker_headers: Speaker.csv_headers,
        story_headers: Story.csv_headers
      )
    end

    def mapped_header_mismatch
      flash.alert = "Additional headers detected. Please verify your CSV headers against the resource you are importing."
      redirect_to import_path
    end
  end
end

rails/app/controllers/dashboard/places_controller.rb
module Dashboard
  class PlacesController < BaseController
    def index
      @page = PlacesPage.new(community_places, meta_params)
      @places = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "places", formats: [:html]),
            pagination: @page.has_next_page? ? places_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    def new
      # set initial position using the current community's theme
      current_theme = current_community.theme
      authorize @place = community_places.new(lat: current_theme.center_lat || 0, long: current_theme.center_long || 0)
    end

    def create
      authorize Place
      @place = community_places.new(place_params)

      if @place.save
        redirect_to @place
      else
        render :new
      end
    end

    def show
      @place = authorize community_places.find(params[:id])
    end

    def edit
      @place = authorize community_places.find(params[:id])
    end

    def update
      @place = authorize community_places.find(params[:id])

      if @place.update(place_params)
        redirect_to @place
      else
        render :edit
      end
    end

    def destroy
      @place = authorize community_places.find(params[:id])

      @place.destroy

      redirect_to places_path
    end

    def delete_photo
      @place = authorize community_places.find(params[:place_id])
      @place.photo.purge

      head :ok
    end

    def delete_name_audio
      @place = authorize community_places.find(params[:place_id])
      @place.name_audio.purge

      head :ok
    end

    private

    def community_places
      policy_scope(current_community.places)
    end

    def place_params
      params.require(:place).permit(
        :name,
        :description,
        :photo,
        :name_audio,
        :type_of_place,
        :region,
        :lat,
        :long,
        story_ids: []
      )
    end
  end
end

rails/app/controllers/dashboard/search_controller.rb
module Dashboard
  class SearchController < BaseController
    def index
      @page = SearchPage.new(current_community, search_params)
      @results = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "results", formats: [:html]),
            pagination: @page.has_next_page? ? search_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    private

    def search_params
      params.permit(
        :search,
        :limit,
        :offset
      )
    end
  end
end

rails/app/controllers/dashboard/speakers_controller.rb
module Dashboard
  class SpeakersController < BaseController
    def index
      @page = SpeakersPage.new(community_speakers, meta_params)
      @speakers = @page.data

      respond_to do |format|
        format.html
        format.json {
          render json: {
            entries: render_to_string(partial: "speakers", formats: [:html]),
            pagination: @page.has_next_page? ? speakers_url(@page.next_page_meta) : nil
          }
        }
      end
    end

    def new
      authorize @speaker = community_speakers.new
    end

    def create
      authorize Speaker
      @speaker = community_speakers.new(speaker_params)

      if @speaker.save
        redirect_to @speaker
      else
        render :new
      end
    end

    def show
      @speaker = authorize community_speakers.find(params[:id])
    end

    def edit
      @speaker = authorize community_speakers.find(params[:id])
    end

    def update
      @speaker = authorize community_speakers.find(params[:id])

      if @speaker.update(speaker_params)
        redirect_to @speaker
      else
        render :edit
      end
    end

    def destroy
      @speaker = authorize community_speakers.find(params[:id])

      @speaker.destroy

      redirect_to speakers_path
    end

    def delete_photo
      @speaker = authorize community_speakers.find(params[:speaker_id])
      @speaker.photo.purge

      head :ok
    end

    private

    def community_speakers
      policy_scope(current_community.speakers)
    end

    def speaker_params
      params.require(:speaker).permit(
        :name,
        :photo,
        :speaker_community,
        :birthdate,
        :birthplace_id,
        story_ids: []
      )
    end
  end
end

rails/app/views/dashboard/places/_form.html.erb
<%= form_with model: @place, multipart: true, class: "form aligned", id: "place_form" do |f| %>
  <%= render partial: "shared/form_errors", locals: { resource: @place } %>

  <%= f.label :name, class: "required" %>
  <%= f.text_field :name, required: true %>

  <%= f.label :name_audio %>
  <%= f.file_field :name_audio %>
  <% if @place.name_audio.attached? %>
  <ul class="filename-list">
  <li class="file-item">
    <%= link_to @place.name_audio.filename, rails_blob_path(@place.name_audio) %>
    <%= link_to place_name_audio_path(@place), class: "delete-link", method: "delete", data: {confirm: t("dashboard.actions.confirm"), turbo_confirm: t("dashboard.actions.confirm"), turbo_method: :delete}, remote: true do %>
      <svg><use href="#icon-cancel"></svg>
    <% end %>
  </li>
  </ul>
  <% end %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 3 %>

  <%= f.label :photo %>
  <%= f.file_field :photo %>

  <%= f.label :type_of_place %>
  <%= f.text_field :type_of_place %>

  <%= f.label :region %>
  <%= f.text_field :region %>

  <%= f.label :story_ids %>
  <div class="checklist">
    <%= f.collection_check_boxes :story_ids, current_community.stories, :id, :title %>
  </div>

  <div class="two-columns">
    <div class="two-columns-left column-fixed-400">
      <%= f.label :lat %>
      <%= f.text_field :lat %>

      <%= f.label :long %>
      <%= f.text_field :long %>
    </div>
    <div class="two-columns-right">
      <div id="placeMap"></div>
    </div>
  </div>

  <%= f.submit %>
<% end %>

<script>
const placeForm = document.querySelector("#place_form");
const placeLatInput = placeForm.querySelector("#place_lat");
const placeLongInput = placeForm.querySelector("#place_long");
const coordinates = [placeLongInput.value, placeLatInput.value]

Terrastories.map_utils.mapgl(<%= current_community.theme.use_maplibre? %>).then(lib => {
  const placeMap = Terrastories.map_utils.interactiveMap(
    lib,
    {
      accessToken: "<%= current_community.theme.mapbox_token %>",
      container: "placeMap", // container ID
      center: coordinates, // starting position [lng, lat]
      hash: false,
      zoom: <%= current_community.theme.zoom || 5 %>, // starting zoom
      style: "<%= current_community.theme.map_style_url %>", // style URL or style object
      basemapStyle: "<%= current_community.theme.basemap_style %>",
      cooperativeGestures: true,
      dragRotate: false,
      pitchWithRotation: false,
      boxZoom: false,
      touchPitch: false,
      touchZoomRotate: false,
    }
  );

  const marker = new lib.Marker({draggable: true}).setLngLat(coordinates)

  placeMap.on("load", () => {
    marker.addTo(placeMap);
  })

  marker.on("dragend", (e) => {
    const { lng, lat } = marker.getLngLat()

    placeMap.setCenter([lng, lat])
  })

  // sync values when the map moves
  placeMap.on('move', () => {
    let { lng, lat } = placeMap.getCenter();
    placeLongInput.value = lng.toFixed(5);
    placeLatInput.value = lat.toFixed(5);
    marker.setLngLat({lng, lat});
  });

  // sync values when input is edited
  placeLongInput.addEventListener("change", (e) => {
    let { lat } = placeMap.getCenter();
    placeMap.setCenter({lng: e.target.value, lat: lat});
  });

  placeLatInput.addEventListener("change", (e) => {
    let { lng } = placeMap.getCenter();
    placeMap.setCenter({lng: lng, lat: e.target.value});
  });

})
</script>

rails/app/views/dashboard/places/_places.html.erb
<% @places.each do |place| %>
  <%= link_to place_path(place), class: "card card--stacked" do %>
    <% if place.photo.attached? %>
      <% if place.photo.variable? %>
        <%= image_tag place.photo.variant(resize_to_limit: [300, 300]), class: "card__img", alt: place.name, title: place.name %>
      <% else %>
        <%= image_tag place.photo, class: "card__img", alt: place.name, title: place.name %>
      <% end %>
    <% else %>
      <%= image_tag asset_path("home-icon.svg"), class: "card__img", alt: place.name, title: place.name, height: 150 %>
    <% end %>
    <div>
      <h3>
        <% if place.region.present? %>
          <span class="card__heading--small"><%= place.region %></span>
        <% end %>
        <%= place.name %>
      </h3>
      <% if place.type_of_place.present? %><span class="badge"><%= place.type_of_place %></span><% end %>
    </div>
    <% if place.description.present? %><p><%= place.description %></p><% end %>
  <% end %>
<% end %>

rails/app/views/dashboard/places/edit.html.erb
<% content_for(:title) do %>
  <%= @place.name %> | <%= t("place") %>
<% end %>

<% content_for(:main_heading) do %>
  <div class="avatar-card">
    <span class="media-with-hover-controls rounded" data-replace-on-delete="<%= asset_path("home-icon.svg") %>">
      <% if @place.photo.attached? %>
        <% if @place.photo.variable? %>
          <%= image_tag @place.photo.variant(resize_to_fill: [300, 300]), alt: @place.name, title: @place.name %>
        <% else %>
          <%= image_tag @place.photo, alt: @place.name, title: @place.name %>
        <% end %>
        <%= link_to place_photo_path(@place), class: "overlay delete-link", method: :delete, data: {confirm: t("dashboard.actions.confirm"), turbo_confirm: t("dashboard.actions.confirm"), turbo_method: :delete}, remote: true do %>
          <span><%= t("dashboard.actions.destroy") %></span>
        <% end %>
      <% else %>
        <%= image_tag asset_path("home-icon.svg"), alt: @place.name, title: @place.name %>
      <% end %>
    </span>
    <h2>
      <% if @place.region %>
        <div class="small">
          <%= @place.region %>
        </div>
      <% end %>
      <%= @place.name %>
      <div class="small">
        <% if @place.type_of_place.present? %>
          <span class="badge"><%= @place.type_of_place %></span>
        <% end %>
      </div>
    </h2>
  </div>
<% end %>

<%= render "form" %>

rails/app/views/dashboard/places/index.html.erb
<% content_for(:title) do %>
  <%= t("places") %>
<% end %>

<% content_for(:main_heading) do %>
<div class="columns">
<h2><%= t("places") %></h2>
<%= link_to t("dashboard.actions.new"), new_place_path, class: "btn" if policy(:place).new? %>
</div>
<% end %>

<div class="infinite-scroll">
  <% if @places.empty? %>
    <p><%= t("list.no_results", resources: t("places").downcase) %></p>
  <% else %>
    <div data-infinite-scroll="entries" class="collection">
      <%= render "places" %>
    </div>
    <div data-infinite-scroll="pagination">
      <%#= Prev/Next Pagination Links for folks that don't use / have JavaScript %>
      <% if @page.meta[:offset] > 0 %>
        <%= link_to t("list.prev"), places_path(request.query_parameters.merge(offset: @page.meta[:offset] - @page.meta[:limit])), rel: "prev" %>
      <% end %>
      <% if @page.meta[:next_offset] %>
        <%= link_to t("list.next"), places_path(request.query_parameters.merge(offset: @page.meta[:next_offset])), rel: "next" %>
      <% end %>
    </div>
  <% end %>
</div>

rails/app/views/dashboard/places/new.html.erb
<% content_for(:title) do %>
  <%= t("dashboard.headings.new_resource", name: t("place")) %>
<% end %>

<% content_for(:main_heading) do %>
  <h2><%= t("dashboard.headings.new_resource", name: t("place")) %></h2>
<% end %>

<%= render "form" %>

rails/app/views/dashboard/places/show.html.erb
<% content_for(:title) do %>
  <%= @place.name %> | <%= t("place") %>
<% end %>

<% content_for(:main_heading) do %>
<div class="columns">
  <div class="avatar-card">
    <% if @place.photo.attached? %>
      <% if @place.photo.variable? %>
        <%= image_tag @place.photo.variant(resize_to_fill: [300, 300]), class: "img--rounded img--mega", alt: @place.name, title: @place.name %>
      <% else %>
        <%= image_tag @place.photo, class: "img--rounded img--mega", alt: @place.name, title: @place.name %>
      <% end %>
    <% else %>
      <%= image_tag asset_path("home-icon.svg"), class: "img--rounded img--mega", alt: @place.name, title: @place.name %>
    <% end %>
    <h2>
      <% if @place.region.present? %>
        <div class="small">
          <%= @place.region %>
        </div>
      <% end %>
      <%= @place.name %>
      <% if @place.name_audio.attached? %>
          <%= audio_tag url_for(@place.name_audio), class: "audio-player" %>
          <svg class="icon audio">
            <use href="#icon-speaker">
          </svg>
        <% end %>
      <div class="small">
        <% if @place.type_of_place.present? %>
          <span class="badge badge-orange"><%= @place.type_of_place %></span>
        <% end %>
      </div>
    </h2>
  </div>
  <div class="actions">
    <%= link_to t("dashboard.actions.edit"), edit_place_path(@place), class: "btn" if policy(@place).edit? %>
    <%= link_to t("dashboard.actions.destroy"), place_path(@place), method: :delete, data: {confirm: t("dashboard.actions.confirm"), turbo_confirm: t("dashboard.actions.confirm"), turbo_method: :delete}, class: "btn btn-danger" if policy(@place).destroy? %>
  </div>
</div>
<% end %>

<div class="two-columns">
  <div class="two-columns-left">
    <p><%= @place.description %></p>
  </div>
  <div class="two-columns-right column-fixed-350">
    <div id="static-map"></div>
  </div>
</div>

<h4><%= t("stories") %></h4>

<div class="collection">
  <% if policy_scope(@place.stories).empty? %>
    <p><%= t("list.no_nested_results", resource: t("place").downcase, resources: t("stories").downcase) %></p>
  <% else %>
    <% policy_scope(@place.stories).each do |story| %>
      <%= link_to story, class: "card" do %>
        <div>
          <h3>
            <span class="card__heading--small"><%= story.topic %></span>
            <%= story.title %>
          </h3>

          <% if story.language.present? %>
            <span class="badge"><%= story.language %></span>
          <% end %>

          <% if story.permission_level.present? %>
            <span class="badge"><%= Story.human_attribute_name("permission_level.#{story.permission_level}") %></span>
          <% end %>

          <p><%= story.desc %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<script type="text/javascript">
let nameAudio = document.querySelector(".icon.audio");
const audioPlayer = document.querySelector(".audio-player");

if (nameAudio !== null) {
  nameAudio.addEventListener("click", function(e) {
    if (audioPlayer.paused) {
      audioPlayer.play();
    } else {
      audioPlayer.pause();
    }
  });

  audioPlayer.addEventListener("play", function(e) {
    nameAudio.classList.add("playing");
  });
  audioPlayer.addEventListener("pause", function(e) {
    nameAudio.classList.remove("playing");
  });
  audioPlayer.addEventListener("ended", function(e) {
    nameAudio.classList.remove("playing");
  });
}

Terrastories.map_utils.staticMap(
  <%= current_community.theme.use_maplibre? %>,
  {
    accessToken: "<%= current_community.theme.mapbox_token %>",
    container: "static-map", // container ID
    center: [<%= @place.long %>, <%= @place.lat %>], // starting position [lng, lat]
    zoom: <%= current_community.theme.zoom %>, // starting zoom
    style: "<%= current_community.theme.map_style_url %>", // style URL or style object
    basemapStyle: "<%= current_community.theme.basemap_style %>",
  },
  <%= raw @place.static_map_markers %>
)
</script>